### ISSUE TITLE
안녕하세요

### ISSUE THREAD

**Issue by kkkapuq** [cjaewon/kakaoEmbed#1]
안녕하세요 구글링하다 사용해보고싶어서 왔는데
npm install kakaoEmbed
을 입력해도 설치가 안되서요.. 혹시 어떻게 사용하는지 알 수 있을까요?
깃헙에서 오픈소스를 활용해보는건 처음이라서... 알려주시면 감사하겠습니다

**Comment by cjaewon** [comment]
@kkkapuq 정말 죄송합니다 😭😭 README.md 에서 실수가 있었네요
`npm install kakaoembed` 로 소문자로 입력해주시면 패키지를 설치하실 수 있습니다!

**Comment by kkkapuq** [comment]
아닙니다 ㅎㅎ 감사합니다!! 오래된글이라 답장안해주실줄알았는데 ㅠㅠ
